name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  test_frontend:
    runs-on: ubuntu-latest
    # env:
    #   working-directory: ./client
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        # - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - working-directory: ${{ env.working-directory }}
      - run: pwd
      - run: npm install
      - run: npm test
        env:
          CI: true
